<a href="https://colab.research.google.com/github/yun-aha/ha-WEB/blob/main/210621.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Positional Arguments 위치기반 매개변수
매개변수가 많아진다면? 각 순서의 변수가 무엇을 의미하는지 기억하기 어려움
** 변수에 이름을 붙여주면 keyword 
** 키워드 기반 매개변수 keyword arguments
(주의사항 : 순서대로)


In [ ]:
name='현정'
price=9999
additional_data='추가데이터'
temporary_data=10.0
options=['옵션1','옵션2','옵션3']
data='1999/9/9'
def checkout(name,price,additional_data,temporary_data,options,data):
  print(name)
  print(price)
  print(additional_data)
  print(temporary_data)
  print(options)
  print(data)
checkout(name,price,additional_data,temporary_data,options,data)

현정
9999
추가데이터
10.0
['옵션1', '옵션2', '옵션3']
1999/9/9


<p>Optional Data</p>
평소 사용하지 않지만 가끔 사용할 때가 있는 경우
함수에는 선언되어 있지 않은데, 입력에는 넣은 경우
<p>*args</p> 
- class 'tuple'



In [ ]:
name='현정'
price=9999
additional_data='추가데이터'
temporary_data=10.0
options=['옵션1','옵션2','옵션3']
data='1999/9/9'
def checkout2(name,*args):
  print(name)
  for arg in args:
    print(arg)
  print(len(args))
checkout2(name,price,additional_data,temporary_data,options,data)

현정
9999
추가데이터
10.0
['옵션1', '옵션2', '옵션3']
1999/9/9
5


<p>keyword arguments + optional data</p>
**kwargs  -> class'dict'

In [ ]:
name='현정'
def checkout3(name,**kwargs):
  print(name)
  print(kwargs.keys())
  print(kwargs.values())
  print(len(kwargs))
checkout3(name,prcie=9999,additional_data='추가데이터',temporary_data=10.0,
          options=['옵션1','옵션2','옵션3'],data='1999/9/9')


현정
dict_keys(['prcie', 'additional_data', 'temporary_data', 'options', 'data'])
dict_values([9999, '추가데이터', 10.0, ['옵션1', '옵션2', '옵션3'], '1999/9/9'])
5


In [ ]:
name='현정'
price=9999
additional_data='추가데이터'
temporary_data=10.0
options=['옵션1','옵션2','옵션3']
data='1999/9/9'
def checkout4(name,*args,**kwargs):
  print(name)
  for arg in args:
    print(arg)
  for kwa in kwargs:
    print(kwa)
  print(kwargs.keys())
  print(kwargs.values())
checkout4(name,price,additional_data,temporary_data,options,data='1999/9/9')

현정
9999
추가데이터
10.0
['옵션1', '옵션2', '옵션3']
data
dict_keys(['data'])
dict_values(['1999/9/9'])


In [ ]:
name='현정'
price=9999
additional_data='추가데이터'
def checkout5(*args,**kwargs):
  for arg in args:
    print(arg)
  for kwa, rgs in kwargs.items():
    print(f'key:{kwa} / value:{rgs}')
checkout5(name, price, additional_data,temporary_data=10.0, 
          options=['옵션1','옵션2','옵션3'], data='1999/9/9')

현정
9999
추가데이터
key:temporary_data / value:10.0
key:options / value:['옵션1', '옵션2', '옵션3']
key:data / value:1999/9/9


<h1><b> < Class ></b></h1>
Programming : 문제를 해결하기 위하여 그 처리방법과 순서를 기술
<p>
1. 절차지향 PP (C)
2. 객체지향 OPP (Java,python, C++,...)
지향한다는 것, 강제x
</p>
절차지향 -> 객체지향의 차이점 : Class


In [ ]:
# 절차지향-장바구니 기능 구현
name='현'
total=0
while True:
  say=input()
  if say=='사과':
    total+=300
  elif say=='바나나':
    total+=680
  elif say=='블루베리':
    total+=1910
  else:
    break
print(name,total)

#
customer='감쟈'
cart=[]
total_price=0
cart.append(('사과',300))
total_price+=300
cart.append(('바나나',680))
total_price+=680
cart.append(('블루베리',1910))
total_price+=1910
print(f'{customer}님, 총 {total_price}주문완료.')

total_price=0
cart.clear()


아악
현 0
감쟈님, 총 2890주문완료.


In [ ]:
class Cart:
  def __init__(self,user):
    self.user=user
    self.total=0
    self.cart_list=[]
  def add_item(self,item):
    self.cart_list.append(item)
    self.total+=item.price
  def checkout(self):
    print(f'{self.user}님 총 금액{self.total}주문완료.')
    self.total=0
    self.cart_list.clear()

class Item:
  def __init__(self,name,price):
    self.name=name
    self.price=price
  
cart=Cart('현')
cart.add_item(Item('사과',300))
cart.add_item(Item('블루베리',1910))
cart.add_item(Item('바나나',680))
cart.checkout()

현님 총 금액2890주문완료.


In [ ]:
customer1='A'
customer2='B'
cart1=[]
fruit1=[]
cart2=[]
total1,total2=0,0
fresh1,fresh2=0,0
cart1.append('사과')
fruit1.append('사과')
total1+=300
fresh1+=9
cart1.append('바나나')
fruit1.append('바나나')
total1+=680
fresh1+=4
cart1.append('블루베리')
fruit1.append('블루베리')
total1+=1910
fresh1+=7
cart1.append('볼펜')
total1+=1100
cart1.append('소파')
total1+=39800
cart2.append('바나나')
total2+=680
cart2.append('사과')
total2+=300
print(f'{customer1}님 {total1}원 주문완료.')
print(f'{customer1}님 신선도는 {fresh1/len(fruit1)}')



A님 43790원 주문완료.
A님 신선도는 6.666666666666667


In [ ]:
class Cart2:
  def __init__(self,customer):
    self.customer=customer
    self.total=0
    self.fresh_list=[]
    self.fresh_total=0
  def add_item(self,item):
    if item.name in ['바나나','사과','블루베리']:
      self.fresh_list.append(item)
      self.fresh_total+=item.fresh
    self.total+=item.price
  def checkout(self):
    print(f'{self.customer}님 총 금액{self.total}주문완료.')
    if self.fresh_total!=0:
      print(f'{self.customer}님 신선도는 {self.fresh_total/len(self.fresh_list)}')
    self.total=0
    self.fresh_list.clear()
    self.fresh_total=0

class Item:
  def __init__(self,name,price,fresh):
    self.name=name
    self.price=price
    self.fresh=fresh

cart1=Cart2('A')
cart2=Cart2('B')
cart1.add_item(Item('사과',300,9))
cart1.add_item(Item('블루베리',1910,7))
cart1.add_item(Item('바나나',680,4))
cart1.add_item(Item('볼펜',1100,0))
cart1.add_item(Item('소파',39800,0))
cart2.add_item(Item('사과',300,9))
cart2.add_item(Item('바나나',680,4))
cart1.checkout()


#isinstance함수 isinstance(object,class)
# 1번째 object가 class에 있는지.? bool값으로 출력

#프로그램 순서와 자료구조 분리

A님 총 금액43790주문완료.
A님 신선도는 6.666666666666667


절차지향 순서와 절차를 먼저 ///
객체지향 사물 혹은 물체의 기능들을 먼저 설계

In [ ]:
class Phone:
  def __init__(self,**kwargs):
    self.user=kwargs['user']
    self.number=kwargs['number']
    self.net=kwargs['net']
    self.s_number=kwargs['s_number']
  def On(self):
    print(f'사용자 : {self.user} - 통신사 : {self.net} 핸드폰 켜지는 중')
    print(f'번호 : {self.number}')
  def call(self,tem):
    print(f'{tem} 전화거는중')
  def message(self,tem):
    print(f'{tem} 문자전송')
  def Off(self):
    print(f'전원을 종료합니다')

phone=Phone(user='현',number='010-999-9999',net='LG',s_number='123')
phone.On()
phone.call('010-111-1111')
phone.message('010-990-9099')
phone.Off()

print('-----------------------------')

class Smartphone(Phone):
  def __init__(self,**kwargs):
    super().__init__(**kwargs)
    self.os=kwargs['os']
  def On(self):
    print(f'{self.user},{self.number}')
  def write(self,tem):
    with open('smartphone.txt','w') as f:
      f.write(tem)
    print(f'입력중')
  def read(self):
    with open('smartphone.txt','r') as f:
      line=f.read()
      print(line)
  
phone2=Smartphone(user='현',number='010-999-9999',net='LG',s_number='123',os='LTE')
phone2.On()
phone2.write('가나다라마바사')
phone2.read()
    

사용자 : 현 - 통신사 : LG 핸드폰 켜지는 중
번호 : 010-999-9999
010-111-1111 전화거는중
010-990-9099 문자전송
전원을 종료합니다
-----------------------------
현,010-999-9999
입력중
가나다라마바사


<h><b>파일 읽기 예제-Html 소스 분석</b></h>


In [ ]:
with open('html_source.txt','r')as f:
  line= f.read()
  ha=line.split('<div class="inner_number">')
  ha.pop(0)
for i in ha:
  print(i.split('</div>')[0])
#encoding='utf-8'

223778
223773
223772
223769
223767
223760
223757
223755
223753
223751
223743
223738
223736
223728
223715


In [ ]:
f=open('html_source.txt','r',encoding='utf-8')
temp=f.read()
splitted=temp.split('<div class="inner_number">')
splitted.pop(0)
for item in splitted:
  print(item.split('</div>')[0])

223778
223773
223772
223769
223767
223760
223757
223755
223753
223751
223743
223738
223736
223728
223715


In [ ]:
from new_package import Phone,Smartphone


array는 정적 할당, list는 동적할당

> (3,2,1), (2,5,3), (7,2), (2,4,3,2), (3,2,4,4)



In [ ]:
import numpy as np
temp=np.zeros((3,2,1))
temp[2][0][0]=1
print(temp)
print('----------')
temp2=np.zeros((2,5,3))
temp2[0][3][1]=1
print(temp2)
print('================')
temp3=np.zeros((7,2))
temp3[1][0]=1
print(temp3)

[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[1.]
  [0.]]]
----------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
temp3=np.zeros((2,4,3,2))
temp3[0][3][2][1]=1
print(temp3)
temp4=np.zeros((3,2,4,4))
temp4[1][1][1][2]=1
print(temp4)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 1.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [ ]:
arr=np.array([1,2,3])
print(arr)

arr2=np.array([(1,2,3),(4,5,6)])
print(arr2)

arr3=np.array([1,2],dtype=np.int64)
print(arr3)
print('------------------------------')
arr4=np.zeros((3,3,3))
print(arr4)

arr5=np.zeros((2,3,5))
print(arr5)
print('-------*----------*-----------*---')
arr6=np.ones((2,2,7))
print(arr6)

arr7=np.ones((2,5,5))
print(arr7)
print('=======================')
arr8=np.array([[[0,1],[5,6],[4,3],[1,0]],[[0,1],[0,6],[5,4],[4,1]]])
print(arr8)

arr9=np.array([[[5,4,4,0],[3,6,1,4]],[[4,2,0,3],[4,5,6,6]]])
print(arr9)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 2]
------------------------------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
-------*----------*-----------*---
[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0 1]
  [5 6]
  [4 3]
  [1 0]]

 [[0 1]
  [0 6]
  [5 4]
  [4 1]]]
[[[5 4 4 0]
  [3 6 1 4]]

 [[4 2 0 3]
  [4 5 6 6]]]


In [ ]:
arr10=np.full((2,5,5),11)
print(arr10)
print('----------------------------')
arr11=np.full((3,2,2),71)
print(arr11)
arr14=np.zeros_like((5,2))
print(arr14)
print('================================')
arr_empty=np.empty((2,3))
print(arr_empty)
arr12=np.arange(0,16,2.5,dtype=float)
print(arr12)
arr13=np.linspace(0,16,num=5)   # num은 들어갈 갯수
print(arr13)

[[[11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]]

 [[11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]
  [11 11 11 11 11]]]
----------------------------
[[[71 71]
  [71 71]]

 [[71 71]
  [71 71]]

 [[71 71]
  [71 71]]]
[0 0]
[[ 2.5  5.   7.5]
 [10.  12.5 15. ]]
[ 0.   2.5  5.   7.5 10.  12.5 15. ]
[ 0.  4.  8. 12. 16.]


In [ ]:
arr15=np.linspace(2,82,10)
print(arr15)
arr16=np.arange(82,2,-3.7)
print(arr16)

[ 2.         10.88888889 19.77777778 28.66666667 37.55555556 46.44444444
 55.33333333 64.22222222 73.11111111 82.        ]
[82.  78.3 74.6 70.9 67.2 63.5 59.8 56.1 52.4 48.7 45.  41.3 37.6 33.9
 30.2 26.5 22.8 19.1 15.4 11.7  8.   4.3]


In [ ]:
arr=np.array([2,1,5,3,7,4,6,8])
arr=np.sort(arr)
print(arr)

arr1=np.array([[1,4],[3,1]])
arr1=np.sort(arr1,axis=0)
print(arr1)

arr2=np.array([[1,5,2,3,0],[9,7,8,6,4]])
arr2=np.sort(arr2,axis=0)
print(arr2)

print('---------------')

arr3=np.array([[[1,4,20,23,28],[13,8,24,21,5]],[[25,29,26,18,2],[14,27,9,10,3]],[[19,15,11,22,0],[6,16,7,17,12]]])
arr3=np.sort(arr3,axis=2)
print(arr3)


[1 2 3 4 5 6 7 8]
[[1 1]
 [3 4]]
[[1 5 2 3 0]
 [9 7 8 6 4]]
---------------
[[[ 1  4 20 23 28]
  [ 5  8 13 21 24]]

 [[ 2 18 25 26 29]
  [ 3  9 10 14 27]]

 [[ 0 11 15 19 22]
  [ 6  7 12 16 17]]]


In [ ]:
arr4=np.searchsorted([1,2,3,4,5],3)
print(arr4)
arr5=np.searchsorted([1,2,3,4,5],3,side='right')
print(arr5)
#들어갈., 인덱스 값 출력 
arr6=np.searchsorted([1,2,3,4,5],[-10,10,2,3])
print(arr6)
#searchsorted == python bisect 이진탐색

2
3
[0 5 1 2]


In [ ]:
arr7=np.array([1,3,11,4])
arr8=np.array([5,6,7,9])
arr78=np.concatenate((arr7,arr8))
print(arr78)

[ 1  3 11  4  5  6  7  9]


In [ ]:
arr9=np.array([[1,3],[49,4]])
arr10=np.array([[7,20],[2,5]])
arr90=np.concatenate((arr9,arr10),axis=1)
print(arr90)
print('-----------')
arr11=np.array([[3,5,4],[1,5,4],[2,7,8]])
arr12=np.array([[10,11,12],[13,17,18],[14,16,15]])
arr112=np.concatenate((arr11,arr12),axis=1)
print(arr112)

[[ 1  3  7 20]
 [49  4  2  5]]
-----------
[[ 3  5  4 10 11 12]
 [ 1  5  4 13 17 18]
 [ 2  7  8 14 16 15]]
